title: DevOps documentation
description: A sick template. wow.
theme: just-the-docs
logo: "/assets/images/water.png"

favicon_ico: "/assets/images/favicon.ico"
color_scheme: light

url: https://katagawa94.github.io

callouts:
  warning:
    title: Warning
    color: red
  dos:
    title: Dos
    color: green
  donts:
    title: Don'ts
    color: red
  note:
    title: note
    color: blue
