title: DevOps documentation
description: A sick template. wow.
theme: just-the-docs
logo: "/assets/images/water.svg"

favicon_ico: "/assets/images/favicon.ico"
color_scheme: dark

url: https://katagawa94.github.io
